### ISSUE TITLE
A little too complex?

### ISSUE THREAD

**Issue by navaru** [dominictarr/sortable#1]
The number of lines of code + jQuery UI dep feels too complex, did you consider building with components (https://github.com/component)?

I would be glad to help you implement something similar in the future based on components, just let me know.

Edit 1: oh.. ui.js is actually only the jQuery UI :) I thought you extended it in some way

**Comment by dominictarr** [comment]
https://github.com/dominictarr/sortable/blob/master/src/jquery.ui.touch-punch.js patches it, to make it work with touch.

I'd like to remove jquery ui, but I used it to get something working asap.

This is intended to be bundled with browserify.
I'm of the opinion that we have a great package manager (npm) that works for the browser (via browserify).
component isn't the answer, the answer is better npm-\* tools.

**Comment by dominictarr** [comment]
jquery-ui is just bundled, I've only prefixed it slightly so it's requireable, and added the patch, but I havn't edited it's code at all.

All the code I wrote is in index.js

**Comment by navaru** [comment]
I've tried browserify for the last days, I like v2, the only way is now I need to find a way to bundle css also. I like it better than component, thanks

**Comment by dominictarr** [comment]
Awesome!

@substack just wrote this module, `https://github.com/substack/brfs` which works with browserify v2 and bundles anything  you load with `fs.readFileSync`

@shtylman recommends https://github.com/shtylman/npm-css which bundles css into one file, so it can be cached.

There are many opinions. I'll let you decide.

**Comment by navaru** [comment]
Thanks for your help!
